// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: game.proto

package shared

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 向き
type Direction int32

const (
	Direction_UP    Direction = 0
	Direction_DOWN  Direction = 1
	Direction_LEFT  Direction = 2
	Direction_RIGHT Direction = 3
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "UP",
		1: "DOWN",
		2: "LEFT",
		3: "RIGHT",
	}
	Direction_value = map[string]int32{
		"UP":    0,
		"DOWN":  1,
		"LEFT":  2,
		"RIGHT": 3,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

// プレイヤーのステータス
type PlayerStatus int32

const (
	PlayerStatus_ALIVE        PlayerStatus = 0
	PlayerStatus_DISCONNECTED PlayerStatus = 1 // サーバーから切断を通知するために使う
	PlayerStatus_DEAD         PlayerStatus = 2 // 弾に当たってやられた状態
)

// Enum value maps for PlayerStatus.
var (
	PlayerStatus_name = map[int32]string{
		0: "ALIVE",
		1: "DISCONNECTED",
		2: "DEAD",
	}
	PlayerStatus_value = map[string]int32{
		"ALIVE":        0,
		"DISCONNECTED": 1,
		"DEAD":         2,
	}
)

func (x PlayerStatus) Enum() *PlayerStatus {
	p := new(PlayerStatus)
	*p = x
	return p
}

func (x PlayerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[1].Descriptor()
}

func (PlayerStatus) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[1]
}

func (x PlayerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerStatus.Descriptor instead.
func (PlayerStatus) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

// プレイヤーからのアクションの種類
type ActionType int32

const (
	ActionType_SHOOT_BULLET ActionType = 0 // 弾の発射
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "SHOOT_BULLET",
	}
	ActionType_value = map[string]int32{
		"SHOOT_BULLET": 0,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[2].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[2]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

// アイテムの種類
type ItemType int32

const (
	ItemType_BULLET ItemType = 0
)

// Enum value maps for ItemType.
var (
	ItemType_name = map[int32]string{
		0: "BULLET",
	}
	ItemType_value = map[string]int32{
		"BULLET": 0,
	}
)

func (x ItemType) Enum() *ItemType {
	p := new(ItemType)
	*p = x
	return p
}

func (x ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[3].Descriptor()
}

func (ItemType) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[3]
}

func (x ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemType.Descriptor instead.
func (ItemType) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

// アイテムのステータス
type ItemStatus int32

const (
	ItemStatus_ACTIVE  ItemStatus = 0
	ItemStatus_REMOVED ItemStatus = 1 // クライアントにアイテムの削除を通知するために使う
)

// Enum value maps for ItemStatus.
var (
	ItemStatus_name = map[int32]string{
		0: "ACTIVE",
		1: "REMOVED",
	}
	ItemStatus_value = map[string]int32{
		"ACTIVE":  0,
		"REMOVED": 1,
	}
)

func (x ItemStatus) Enum() *ItemStatus {
	p := new(ItemStatus)
	*p = x
	return p
}

func (x ItemStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[4].Descriptor()
}

func (ItemStatus) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[4]
}

func (x ItemStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemStatus.Descriptor instead.
func (ItemStatus) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

// 位置情報
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// プレイヤーの状態
type PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Position      *Position              `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Direction     Direction              `protobuf:"varint,3,opt,name=direction,proto3,enum=samplerealtimeserver.Direction" json:"direction,omitempty"`
	Status        PlayerStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=samplerealtimeserver.PlayerStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerState) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerState) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PlayerState) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_UP
}

func (x *PlayerState) GetStatus() PlayerStatus {
	if x != nil {
		return x.Status
	}
	return PlayerStatus_ALIVE
}

// 接続直後にサーバーがクライアントへ1度だけ送る初期化情報
type Welcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerState   *PlayerState           `protobuf:"bytes,1,opt,name=player_state,json=playerState,proto3" json:"player_state,omitempty"`
	MapWidth      int32                  `protobuf:"varint,2,opt,name=map_width,json=mapWidth,proto3" json:"map_width,omitempty"`
	MapHeight     int32                  `protobuf:"varint,3,opt,name=map_height,json=mapHeight,proto3" json:"map_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *Welcome) GetPlayerState() *PlayerState {
	if x != nil {
		return x.PlayerState
	}
	return nil
}

func (x *Welcome) GetMapWidth() int32 {
	if x != nil {
		return x.MapWidth
	}
	return 0
}

func (x *Welcome) GetMapHeight() int32 {
	if x != nil {
		return x.MapHeight
	}
	return 0
}

// プレイヤーからのアクション
type PlayerActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ActionType             `protobuf:"varint,1,opt,name=type,proto3,enum=samplerealtimeserver.ActionType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerActionRequest) Reset() {
	*x = PlayerActionRequest{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerActionRequest) ProtoMessage() {}

func (x *PlayerActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerActionRequest.ProtoReflect.Descriptor instead.
func (*PlayerActionRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerActionRequest) GetType() ActionType {
	if x != nil {
		return x.Type
	}
	return ActionType_SHOOT_BULLET
}

// アイテムの状態
type ItemState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Type          ItemType               `protobuf:"varint,2,opt,name=type,proto3,enum=samplerealtimeserver.ItemType" json:"type,omitempty"`
	Position      *Position              `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Status        ItemStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=samplerealtimeserver.ItemStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemState) Reset() {
	*x = ItemState{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemState) ProtoMessage() {}

func (x *ItemState) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemState.ProtoReflect.Descriptor instead.
func (*ItemState) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *ItemState) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ItemState) GetType() ItemType {
	if x != nil {
		return x.Type
	}
	return ItemType_BULLET
}

func (x *ItemState) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *ItemState) GetStatus() ItemStatus {
	if x != nil {
		return x.Status
	}
	return ItemStatus_ACTIVE
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x14samplerealtimeserver\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"\xe1\x01\n" +
	"\vPlayerState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12:\n" +
	"\bposition\x18\x02 \x01(\v2\x1e.samplerealtimeserver.PositionR\bposition\x12=\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x1f.samplerealtimeserver.DirectionR\tdirection\x12:\n" +
	"\x06status\x18\x04 \x01(\x0e2\".samplerealtimeserver.PlayerStatusR\x06status\"\x8b\x01\n" +
	"\aWelcome\x12D\n" +
	"\fplayer_state\x18\x01 \x01(\v2!.samplerealtimeserver.PlayerStateR\vplayerState\x12\x1b\n" +
	"\tmap_width\x18\x02 \x01(\x05R\bmapWidth\x12\x1d\n" +
	"\n" +
	"map_height\x18\x03 \x01(\x05R\tmapHeight\"K\n" +
	"\x13PlayerActionRequest\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2 .samplerealtimeserver.ActionTypeR\x04type\"\xce\x01\n" +
	"\tItemState\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x122\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1e.samplerealtimeserver.ItemTypeR\x04type\x12:\n" +
	"\bposition\x18\x03 \x01(\v2\x1e.samplerealtimeserver.PositionR\bposition\x128\n" +
	"\x06status\x18\x04 \x01(\x0e2 .samplerealtimeserver.ItemStatusR\x06status*2\n" +
	"\tDirection\x12\x06\n" +
	"\x02UP\x10\x00\x12\b\n" +
	"\x04DOWN\x10\x01\x12\b\n" +
	"\x04LEFT\x10\x02\x12\t\n" +
	"\x05RIGHT\x10\x03*5\n" +
	"\fPlayerStatus\x12\t\n" +
	"\x05ALIVE\x10\x00\x12\x10\n" +
	"\fDISCONNECTED\x10\x01\x12\b\n" +
	"\x04DEAD\x10\x02*\x1e\n" +
	"\n" +
	"ActionType\x12\x10\n" +
	"\fSHOOT_BULLET\x10\x00*\x16\n" +
	"\bItemType\x12\n" +
	"\n" +
	"\x06BULLET\x10\x00*%\n" +
	"\n" +
	"ItemStatus\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x00\x12\v\n" +
	"\aREMOVED\x10\x01B&Z$realtime-communication-server/sharedb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_game_proto_goTypes = []any{
	(Direction)(0),              // 0: samplerealtimeserver.Direction
	(PlayerStatus)(0),           // 1: samplerealtimeserver.PlayerStatus
	(ActionType)(0),             // 2: samplerealtimeserver.ActionType
	(ItemType)(0),               // 3: samplerealtimeserver.ItemType
	(ItemStatus)(0),             // 4: samplerealtimeserver.ItemStatus
	(*Position)(nil),            // 5: samplerealtimeserver.Position
	(*PlayerState)(nil),         // 6: samplerealtimeserver.PlayerState
	(*Welcome)(nil),             // 7: samplerealtimeserver.Welcome
	(*PlayerActionRequest)(nil), // 8: samplerealtimeserver.PlayerActionRequest
	(*ItemState)(nil),           // 9: samplerealtimeserver.ItemState
}
var file_game_proto_depIdxs = []int32{
	5, // 0: samplerealtimeserver.PlayerState.position:type_name -> samplerealtimeserver.Position
	0, // 1: samplerealtimeserver.PlayerState.direction:type_name -> samplerealtimeserver.Direction
	1, // 2: samplerealtimeserver.PlayerState.status:type_name -> samplerealtimeserver.PlayerStatus
	6, // 3: samplerealtimeserver.Welcome.player_state:type_name -> samplerealtimeserver.PlayerState
	2, // 4: samplerealtimeserver.PlayerActionRequest.type:type_name -> samplerealtimeserver.ActionType
	3, // 5: samplerealtimeserver.ItemState.type:type_name -> samplerealtimeserver.ItemType
	5, // 6: samplerealtimeserver.ItemState.position:type_name -> samplerealtimeserver.Position
	4, // 7: samplerealtimeserver.ItemState.status:type_name -> samplerealtimeserver.ItemStatus
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		EnumInfos:         file_game_proto_enumTypes,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
